<rules>
	<rule	Name="DontDestroyStackTrace" 
		Type="Gendarme.Rules.Exceptions.DontDestroyStackTrace, Gendarme.Rules.Exceptions, Version=0.0.3.1, Culture=neutral, PublicKeyToken=null"
		Uri="http://www.mono-project.com/Gendarme#DontDestroyStackTraceRule" >
		<problem>A catch block in method or property '{0}' throws the caught exception.</problem>
		<solution>If you need to throw the exception caught by the catch block, use 'throw;' instead of 'throw ex;'</solution>
	</rule>
</rules>
